Au fil des années Python est devenu un outil du quotidien pour les ingénieurs et chercheurs de toutes les disciplines scientifiques. Grâce à de très nombreuses librairies d'une grande qualité il permet aujourd'hui d'égaler, voire de surpasser des solutions propriétaires les plus performantes du marché. Il est devenu un des outils incontournables des Data Scientists. Nous allons nous intéresser ici à une des bibliothèques Python les plus utilisées : NumPy.

NumPy (pour Numerical Python) est une bibliothèque numérique apportant un support efficace pour la création et la manipulation de larges tableaux multidimensionnels, et de routines mathématiques de haut niveau (algèbre linéaire, statistiques, fonctions mathématiques complexes etc...). NumPy a été initialement développée au milieu des années 2000, et est issu d'un package encore plus ancien appelé Numeric. L'ancienneté de cette bibliothèque implique qu'un grand nombre d'analyses de données sur Python exploitent NumPy d'une manière ou d'une autre.

Cette formation donne un aperçu des possibilités extrêmement vastes proposées par NumPy. Pour compléter ce module n'hésitez pas à vous référer à la documentation fournie et claire. Tout au long de la formation vous serez systématiquement redirigé vers la documentation pour que vous puissiez vous familiariser avec les différents outils proposés .

https://numpy.org/doc/stable/reference/

Resume

In [ ]:
import numpy as np 


#cree un np :
print ('----------------------------- Creation np')
a = np.array ([[1,3,5,7],[2,4,6,8]])  #cree a partir d une liste
print ('arange',np.arange(0,10,4))  #range np
print ('linspace',np.linspace(0,8,11))  #du start a end avec n nombre


#cree un special np type :
#print ('----------------------------- Creation np special ')
#print (np.ones((3,4)))      #table de 1
#print (np.zeros((3,2)))  #table de 0
#print (np.eye(3) )  #table diagonale
#print (np.diag(np.ones((2)), -1))   #table diagonale


#modifie un np :
print ('----------------------------- Modifier un np')
print (a.shape) #attribut forme
print ('a\n', a)
a = a.transpose() #col = ligne et ligne = col
print ('a\n', a)
print (a.shape) #attribut forme
a = a.reshape(2,4)  #determine la forme 
#a = a[np.newaxis, :] #ajoute un dimension au tableau


#Slicing 
print ('----------------------------- Slicing de np')
print ('a')
print (a)
print('\na[:1] la ligne ')
print (a[:1])
print('\na[:][:2] la colonne ')
print (a[0:,2])
print('\na[1][1] les deux')
print (a[1][1])
print ('Slicing contidionel : a[(a>2) & (a<6)]')
print (a[(a>2) & (a<6)])

#fonction Statistique
a.mean() # moyenne sur tout le tableau
a.mean(axis = 0) # moyenne sur les colonnes
a.mean(axis = 1) # moyenne sur les lignes
#Il existe plusieurs autres méthodes qui se comportent comme la méthode mean, tel que:
a.sum ()# - pour calculer la somme d'un tableau
a.std ()# - calcul l'écart type
a.min ()# - trouve l'élément minimum
a.max ()# - trouve l'élément maximum

# fonction random
print (np.random.random((3,2))) #des valeurs aléatoires
print (np.random.randint(1,100,10)) #valeurs int aléatoires
np.random.randn(2,3) #distribution normale ou gossiene
np.random.rand(4,3) #distribution uniforme

#separe/reunis des np :
print ('----------------------------- separe/reunis des np')
a,b,c = np.array_split(np.arange(1,31),3) #split en n (ici en 3 a,b,c)
print ('a  ',a)
print ('b  ',b)
print ('c  ',c)
d = np.concatenate((a,b,c)).reshape(5,6) #concat"
print ('d \n',d)

#attribut :
print ('----------------------------- attribut np')
print ('ndim\n',a.ndim)
print ('shape\n',a.shape)
print ('size\n',a.size)
print ('dtype\n',a.dtype)

#fonction :
#Redimensionner: reshape, ravel, resize, transpose
#Empiler : column_stack, concatenate, vstack
#Fractionner : array_split, vsplit
#Ordonner : sort, argmax, argmin, argsort, max, min


Cours : 

Création d'un Numpy array

In [5]:
import numpy as np 

#creation de 
my_vect  = np.array (list(range(0,9))) 
my_mat = np.array ([[1,2,3],[0,4,5],[6,7,8]])


print ('table de type',type (my_vect )) #table de type nd array

print ('\ntable unidimentionnel ou vecteur\n',my_vect  )
print ('\ntable bidimentionnel ou matrice\n',my_mat )


table de type <class 'numpy.ndarray'>

table unidimentionnel ou vecteur
 [0 1 2 3 4 5 6 7 8]

table bidimentionnel ou matrice
 [[1 2 3]
 [0 4 5]
 [6 7 8]]


In [8]:
# fct reshape()

a = np.array([1,3,8,9,12,15])
print (a)
a=  a.reshape(2,3)
print('fct reshape retourne une nouvelle forme de la table ')
print (a)


[ 1  3  8  9 12 15]
fct reshape
[[ 1  3  8]
 [ 9 12 15]]


In [21]:
#fct arange 

print ("""la fct arange est identique a la fct range mais 
       pour numpy tres simple d utilisation et associé 
       a la fonction reshape().
       Lorsque la fonction arange() est utilisée 
       avec des arguments réels (floats)
       """)
np.arange(0, 20, 2)

la fct arange est identique a la fct range mais 
       pour numpy tres simple d utilisation et associé 
       a la fonction reshape().
       Lorsque la fonction arange() est utilisée 
       avec des arguments réels (floats)
       


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [24]:
#fct np.linspace()

print ("""permet de partir de 0 (start) a 2 (end) et d avoir 9 elements""")

np.linspace( 0, 2, 9 )

permet de partir de 0 (start) a 2 (end) et d avoir 9 elements


array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [53]:
print ('-----------------------------------------')
print ('fonction   np.ones((ligne,colone)) ')

print("""np.ones((n,p)) crée un array de dimension  n×p  
        rempli de 1. 
        C est un tupple \n""")
np.ones((3,4))


print ('\n')
print ('-----------------------------------------')
print ('fonction  np.zeros((ligne,colone,multiplier))  ')

print("""np.zeros((n,p,l)) crée un array de dimension  
        n×p×l rempli de 0. \n""")

#print (np.zeros((3,2,4)) )
print (np.zeros((3,2)) )


print ('\n')
print ('-----------------------------------------')
print ('fonction  np.eye(n)  ')

print("""np.eye(n) crée un array de la forme 
d'une matrice identité de dimension  n×nn×n , 
c'est à dire un tableau où toutes les valeurs 
sont nulles sauf sur la diagonale, où elles valent 1.\n""",)

print (np.eye(3) )


print ('\n')
print ('-----------------------------------------')
print ('fonction  np.diag(a, i)   ')

print("""np.diag(a, i) crée un array à partir 
d'une séquence a (liste, tuple, array unidimensionnel...) 
en place a sur la i-ème diagonale de la matrice 
(0 étant la diagonale principale,
 -1 celle en dessous, 1 celle au dessus etc..)\n""",)

print ('diagonale haut \n', np.diag(np.ones((2)), 1)) #table de 3 diag haut
print ('\ndiagonale bas \n', np.diag(np.ones((2)), -1)) #table de 3 diag haut


-----------------------------------------
fonction   np.ones((ligne,colone)) 
np.ones((n,p)) crée un array de dimension  n×p  
        rempli de 1. 
        C est un tupple 



-----------------------------------------
fonction  np.zeros((ligne,colone,multiplier))  
np.zeros((n,p,l)) crée un array de dimension  
        n×p×l rempli de 0. 

[[0. 0.]
 [0. 0.]
 [0. 0.]]


-----------------------------------------
fonction  np.eye(n)  
np.eye(n) crée un array de la forme 
d'une matrice identité de dimension  n×nn×n , 
c'est à dire un tableau où toutes les valeurs 
sont nulles sauf sur la diagonale, où elles valent 1.

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


-----------------------------------------
fonction  np.diag(a, i)   
np.diag(a, i) crée un array à partir 
d'une séquence a (liste, tuple, array unidimensionnel...) 
en place a sur la i-ème diagonale de la matrice 
(0 étant la diagonale principale,
 -1 celle en dessous, 1 celle au dessus etc..)

diagonale haut 
 [[0. 1. 0.]
 [0. 0. 1.]


np.random

In [89]:
print ('-----------------------------------------')
print ('fonction  np.random.random((ligne,colone))    ')

print("""np.random.random((n,p)) crée un array 
        avec des valeurs aléatoires.\n""",)
print (np.random.random((3,2)))

print ('\n')
print ('-----------------------------------------')
print ('fonction  np.random.randint((start,stop, nombre))    ')
print("""np.random.randint((n,p,nbr)) crée un array 
        avec des valeurs int aléatoires.\n""",)
print (np.random.randint(1,100,10))


print ('\n')
print ('-----------------------------------------')
print ('fonction  np.random.randn((ligne,cologne))    ')
print ('cree un array avec unedistribution normale ou gossiene')
print ('chiffre prochede 0 on plus de chance de sortir')
np.random.randn(2,3)

print ('\n')
print ('-----------------------------------------')
print ('fonction  np.random.rand((ligne,cologne))    ')
print ('cree un array avec unedistribution uniforme')
print ('chiffre on tous la mm chance de sortir')
np.random.rand(4,3)

-----------------------------------------
fonction  np.random.random((ligne,colone))    
np.random.random((n,p)) crée un array 
        avec des valeurs aléatoires.

[[0.43269585 0.03398714]
 [0.36793716 0.86259236]
 [0.97508841 0.30715103]]


-----------------------------------------
fonction  np.random.randint((start,stop, nombre))    
np.random.randint((n,p,nbr)) crée un array 
        avec des valeurs int aléatoires.

[67 16 60 61 37  4 57 62 20 68]


-----------------------------------------
fonction  np.random.randn((ligne,cologne))    
cree un array avec unedistribution normale ou gossiene
chiffre prochede 0 on plus de chance de sortir


-----------------------------------------
fonction  np.random.rand((ligne,cologne))    
cree un array avec unedistribution uniforme
chiffre on tous la mm chance de sortir


array([[0.21529007, 0.64339917, 0.3763757 ],
       [0.31307726, 0.59177811, 0.42925652],
       [0.48780063, 0.92888849, 0.61806359],
       [0.67854153, 0.34360285, 0.62077165]])

Attributs et fonctions

Les principaux attributs permettant de décrire un tableau de type ndarray sont :

ndarray.ndim: renvoie le nombre de dimensions de l' array. En langage Python le nombre de dimension est appelé le rang.

ndarray.shape: renvoie les dimensions de l'array, ie. la taille de l'array dans chaque dimension.

ndarray.size : renvoie le nombre total d'éléments de l'array.

ndarray.dtype : un objet décrivant le type des éléments de l'array.

Il existe dans Numpy des fonctions pré-définies faites pour la manipulation de tableaux array. Voici une liste en reprenant les principales :

Redimensionner: reshape, ravel, resize, transpose
Empiler : column_stack, concatenate, vstack
Fractionner : array_split, vsplit
Ordonner : sort, argmax, argmin, argsort, max, min

In [86]:
#Slicing conditionel
M = np.array([[21,4,35,60,18],[1,12,7,39,28],[22,86,71,5,23]])
#Insérez votre code ici
print ('Slicing contidionel : M[(M>20) & (M<40)]')
M[(M>20) & (M<40)]

Slicing contidionel : M[(M>20) & (M<40)]


array([21, 35, 39, 28, 22, 23])

In [106]:
#Slicing
#Le symbole : permet de sélectionner tous les éléments 
#à partir de l'index de départ jusqu'à l'indice de fin exclu.
print ('M')
print (M)
print('\nM[:1] la ligne ')
print (M[:1])

print('\nM[:][:2] la colonne ')
print (M[0:,2])

print('\nM[1][1] les deux')
print (M[1][1])

M
[[21  4 35 60 18]
 [ 1 12  7 39 28]
 [22 86 71  5 23]]

M[:1] la ligne 
[[21  4 35 60 18]]

M[:][:2] la colonne 
[35  7 71]

M[1][1] les deux
12


In [64]:
print ('fct split et concatenate :\n')
a,b,c = np.array_split(np.arange(1,31),3)
print ('a  ',a)
print ('b  ',b)
print ('c  ',c)

d = np.concatenate((a,b,c)).reshape(10,3)
print ('d \n',d)

fct split et concatenate :

a   [ 1  2  3  4  5  6  7  8  9 10]
b   [11 12 13 14 15 16 17 18 19 20]
c   [21 22 23 24 25 26 27 28 29 30]
d 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]]


operation arithemetique

In [76]:
#addition 
print ('addition ')
a=np.array ([10,20,30,40])
b=np.arange(1,5)

c = a-b
print (a)
print (b)
print ('a-b = ',c)

print ('\nmutliplication ')
#multiplication
A = np.array( [[1,2], [0,1]] )
B = np.array( [[3,2], [1,0]] )
print(A*B)

print('\n',np.dot(A,B))


print ('\ndivition ')
print ('A*3 = \n', A*3)


addition 
[10 20 30 40]
[1 2 3 4]
a-b =  [ 9 18 27 36]

mutliplication 
[[3 4]
 [0 0]]

 [[5 2]
 [1 0]]

divition 
A*3 = 
 [[3 6]
 [0 3]]


In [78]:
mat = np.zeros(5)
a = np.diag(np.ones(4),-1)
b = np.diag(np.ones(3), -2)*2
c = np.diag(np.ones(2), -3)*3
d = np.diag(np.ones(1),-4)*4 

mat = mat+a+b+c+d
mat = mat + np.transpose(mat)

print(mat)

[[0. 1. 2. 3. 4.]
 [1. 0. 1. 2. 3.]
 [2. 1. 0. 1. 2.]
 [3. 2. 1. 0. 1.]
 [4. 3. 2. 1. 0.]]


Broadcasting

Lorsque l'on effectue des opérations ou que l'on exécute des fonctions sur des tableaux de dimensions différentes, NumPy effectue dans certains ca ce que l'on appelle du Broadcasting pour essayer de faire correspondre les éléments.

Nous avons déjà vu le Broadcasting à l'oeuvre plus haut lors des opérations sur les arrays. Lorsque l'on rajoute une constante c à une matrice M de taille  3×33×3  par exemple, on peut imaginer que l'opération se fait entre la matrice M et une matrice  3×33×3  remplie de c.

Les règles du Broadcasting sont les suivantes:

Deux arrays sont compatibles (broadcastable) si, pour chaque dimension, soit les tailles sont égales, soit l’une d’elles est exactement égale à 1. Par exemple, (6, 3) et (1, 3) sont des formats compatibles, (6, 3) et (6, 1) également, mais (6, 3) et (3, 1) non.

Si un arrays a une dimension de taille 1, ce dernier sera reproduit autant de fois que nécessaire le long de cette dimension pour attendre la taille de l’autre array. Par exemple. un tableau (4, 1, 2) pourra être transformé en tableau (4, 5 2) en le dupliquant 5 fois le long de la deuxième dimension.

Si deux arrays n'ont pas le même nombre de dimensions, alors la dimension de l'array le plus petit sera précédée d’autant de "1" que nécessaire pour atteindre le même rang. Par exemple, si l'on souhaite multiplier deux tableaux de dimensions (7, 2, 1) et (4,): La dimension du second deviendra (1, 1, 4), puis celle du premier (7, 2, 4).

Voici quelques exemples du fonctionnement du broadcasting :

In [83]:

print ('fct newaxis \npour ajouter une dimention a notre table')
a = np.arange(5)
print (a.shape)

a = a[np.newaxis, :]
print (a.shape)

fct newaxis 
pour ajouter une dimention a notre table
(5,)
(1, 5)


Les méthodes statistiques

En plus des opérations mathématiques courantes, NumPy dispose également de plusieurs méthodes que vous pouvez utiliser pour des calculs plus complexes sur des tableaux.
Exemple :

mon_array.mean() # moyenne sur tout le tableau
mon_array.mean(axis = 0) # moyenne sur les colonnes
mon_array.mean(axis = 1) # moyenne sur les lignes
Il existe plusieurs autres méthodes qui se comportent comme la méthode mean, tel que:
sum - pour calculer la somme d'un tableau
std - calcul l'écart type
min - trouve l'élément minimum
max - trouve l'élément maximum

In [139]:
import numpy as np 


#cree un np :
print ('----------------------------- Creation np')
a = np.array ([[1,3,5,7],[2,4,6,8]])  #cree a partir d une liste
print ('arange',np.arange(0,10,4))  #range np
print ('linspace',np.linspace(0,8,11))  #du start a end avec n nombre


#cree un special np type :
#print ('----------------------------- Creation np special ')
#print (np.ones((3,4)))      #table de 1
#print (np.zeros((3,2)))  #table de 0
#print (np.eye(3) )  #table diagonale
#print (np.diag(np.ones((2)), -1))   #table diagonale


#modifie un np :
print ('----------------------------- Modifier un np')
print (a.shape) #attribut forme
print ('a\n', a)
a = a.transpose() #col = ligne et ligne = col
print ('a\n', a)
print (a.shape) #attribut forme
a = a.reshape(2,4)  #determine la forme 
#a = a[np.newaxis, :] #ajoute un dimension au tableau


#Slicing 
print ('----------------------------- Slicing de np')
print ('a')
print (a)
print('\na[:1] la ligne ')
print (a[:1])
print('\na[:][:2] la colonne ')
print (a[0:,2])
print('\na[1][1] les deux')
print (a[1][1])
print ('Slicing contidionel : a[(a>2) & (a<6)]')
print (a[(a>2) & (a<6)])

#fonction Statistique
a.mean() # moyenne sur tout le tableau
a.mean(axis = 0) # moyenne sur les colonnes
a.mean(axis = 1) # moyenne sur les lignes
#Il existe plusieurs autres méthodes qui se comportent comme la méthode mean, tel que:
a.sum ()# - pour calculer la somme d'un tableau
a.std ()# - calcul l'écart type
a.min ()# - trouve l'élément minimum
a.max ()# - trouve l'élément maximum

# fonction random
print (np.random.random((3,2))) #des valeurs aléatoires
print (np.random.randint(1,100,10)) #valeurs int aléatoires
np.random.randn(2,3) #distribution normale ou gossiene
np.random.rand(4,3) #distribution uniforme

#separe/reunis des np :
print ('----------------------------- separe/reunis des np')
a,b,c = np.array_split(np.arange(1,31),3) #split en n (ici en 3 a,b,c)
print ('a  ',a)
print ('b  ',b)
print ('c  ',c)
d = np.concatenate((a,b,c)).reshape(5,6) #concat"
print ('d \n',d)

#attribut :
print ('----------------------------- attribut np')
print ('ndim\n',a.ndim)
print ('shape\n',a.shape)
print ('size\n',a.size)
print ('dtype\n',a.dtype)

#fonction :
#Redimensionner: reshape, ravel, resize, transpose
#Empiler : column_stack, concatenate, vstack
#Fractionner : array_split, vsplit
#Ordonner : sort, argmax, argmin, argsort, max, min






----------------------------- Creation np
arange [0 4 8]
linspace [0.  0.8 1.6 2.4 3.2 4.  4.8 5.6 6.4 7.2 8. ]
----------------------------- Modifier un np
(2, 4)
a
 [[1 3 5 7]
 [2 4 6 8]]
a
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
(4, 2)
----------------------------- Slicing de np
a
[[1 2 3 4]
 [5 6 7 8]]

a[:1] la ligne 
[[1 2 3 4]]

a[:][:2] la colonne 
[3 7]

a[1][1] les deux
6
Slicing contidionel : a[(a>2) & (a<6)]
[3 4 5]
[[0.33265852 0.85205727]
 [0.37749793 0.94090772]
 [0.15018178 0.3922715 ]]
[70 37 11 38 62 12 57 63  8 80]
----------------------------- separe/reunis des np
a   [ 1  2  3  4  5  6  7  8  9 10]
b   [11 12 13 14 15 16 17 18 19 20]
c   [21 22 23 24 25 26 27 28 29 30]
d 
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]
----------------------------- attribut np
ndim
 1
shape
 (10,)
size
 10
dtype
 int32
